try测试代码块错误

catch处理错误代码所运行的代码

try{

}carch(err){

}

